'use client';
/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { ContactPage } from './contact-page';
import { PublishedWork } from './published-work';
import { brandPages, sourceFor } from '@/lib/sources';
import { VideoPlayer } from './video-player';
import { useReveal } from './use-reveal';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, ArrowLeft, Play, Sun, Moon, Menu, X, Download, Mail, MessageCircle, FileText, Volume2 } from 'lucide-react';
import { asset, route, projects, services, categories, contact, videoTitles, durations, type Language, type Project, type Category } from '@/lib/content';
type Props={lang:Language;page:'home'|'work'|'about'|'contact';slug?:string};
const label=(lang:Language,en:string,ar:string)=>lang==='ar'?ar:en;
function Linkedin({size=24}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M7.5 10v7M7.5 7v.1M11 17v-7m0 3a3 3 0 0 1 6 0v4"/></svg>}
function SectionIntro({eyebrow,title,description}:{lang:Language;eyebrow:string;title:string;description?:string}){return <div className="section-intro"><p className="eyebrow"><span/>{eyebrow}</p><h2>{title}</h2>{description&&<p className="section-description">{description}</p>}</div>}
function ProjectCard({project,lang,index=0}:{project:Project;lang:Language;index?:number}){return <Link href={route(lang,`work/${project.slug}`)} className={`project-card ${project.color}`}><div className={`project-art ${project.category}`}>
 {project.category==='strategy'?<div className="strategy-art"><div className="paper-sheet"><small>CREATIVO / AUDIENCE NOTES</small><span>{label(lang,'People first.','الجمهور أولًا.')}</span><div className="paper-lines"/><div className="persona-row"><i/><i/><i/></div><p>ENGLISH · GERMAN · SPANISH</p></div><span className="paper-stamp">{label(lang,'CONTENT PLANNING','تخطيط المحتوى')}</span></div>:<img src={asset(project.cover)} alt={project.subtitle[lang]} loading={index<2?'eager':'lazy'} width="720" height="720"/>}
 <span className="project-brand">{project.brand}</span><span className="project-open" aria-hidden="true">{project.category==='video'?<Play size={21} fill="currentColor"/>:<ArrowUpRight size={24}/>}</span>
 {project.category==='video'&&<span className="video-count">{project.videos?.length} {label(lang,'FILMS','فيديو')}</span>}</div>
 <div className="project-info"><p className="eyebrow">{categories[project.category][lang]}</p><h3>{project.title[lang]}</h3><p>{project.role[lang]}</p></div></Link>}
function VideoTile({id,lang,onPlay}:{id:string;lang:Language;onPlay:(id:string)=>void}){const source=sourceFor(id);return <div className="reel-item"><button className="reel" onClick={()=>onPlay(id)} aria-label={`${label(lang,'Play','تشغيل')}: ${videoTitles[id][lang]}`}><img src={asset(`/images/${id}.jpg`)} alt="" loading="lazy" width="360" height="640"/><span className="reel-duration">{durations[id]}</span><span className="reel-play"><Play size={24} fill="currentColor"/></span><span className="reel-caption"><small>{label(lang,'SCRIPT & EDIT','سكريبت ومونتاج')}</small><strong>{videoTitles[id][lang]}</strong><ArrowUpRight size={20}/></span></button>{source&&<a className="media-source-link" href={source} target="_blank" rel="noopener noreferrer">{label(lang,'View original on Facebook','عرض الأصل على فيسبوك')}<ArrowUpRight size={16}/></a>}</div>}

function ContactBand({lang}:{lang:Language}){return <section className="contact-band"><div className="container contact-band-inner"><div><p className="eyebrow">{label(lang,'HAVE SOMETHING IN MIND?','عندك فكرة؟')}</p><h2>{label(lang,'Let’s make it','خلّينا نحوّلها')} <em>{label(lang,'worth sharing.','لمحتوى يستاهل.')} </em></h2></div><Link href={route(lang,'contact')} className="round-link" aria-label={label(lang,'Get in touch','تواصل معي')}><ArrowUpRight size={40}/></Link></div></section>}
export function Portfolio({lang,page,slug}:Props){
 const [menu,setMenu]=useState(false);const [filter,setFilter]=useState<Category|'all'>('all');const [media,setMedia]=useState<{kind:'video'|'image';id:string}|null>(null);
 const dialog=useRef<HTMLDialogElement>(null);const previousFocus=useRef<HTMLElement|null>(null);
 const t=(en:string,ar:string)=>label(lang,en,ar);const project=projects.find(p=>p.slug===slug);const currentPath=page==='home'?'':slug?`work/${slug}`:page;
 useReveal(`${lang}-${page}-${slug || ''}-${filter}`);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';try{localStorage.setItem('shimaa-language',lang)}catch{}},[lang]);
 useEffect(()=>{if(!media)return;previousFocus.current=document.activeElement as HTMLElement;const d=dialog.current;if(d&&!d.open)d.showModal();const original=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=original;if(d?.open)d.close();previousFocus.current?.focus();}},[media]);
 useEffect(()=>{if(!menu)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setMenu(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[menu]);
 function toggleTheme(){document.documentElement.classList.add('theme-changing');window.setTimeout(()=>document.documentElement.classList.remove('theme-changing'),450);const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('shimaa-theme',next)}catch{}}
 function play(id:string){setMedia({kind:'video',id})}

 return <div className="site" dir={lang==='ar'?'rtl':'ltr'} lang={lang}>
 <a className="skip-link" href="#main">{t('Skip to content','انتقل للمحتوى')}</a>
 <header className="header"><div className="container header-inner"><Link href={route(lang)} className="wordmark" aria-label={t('Shimaa Essam home','شيماء عصام — الرئيسية')}><span className="monogram">s.</span><span>{t('Shimaa Essam','شيماء عصام')}<small>{t('CONTENT CREATOR','صانعة محتوى')}</small></span></Link>
 <nav className="desktop-nav" aria-label={t('Main navigation','القائمة الرئيسية')}>{(['home','work','about','contact'] as const).map((p,i)=><Link key={p} href={route(lang,p==='home'?'':p)} aria-current={page===p?'page':undefined}>{[t('Home','الرئيسية'),t('Work','الأعمال'),t('About','عنّي'),t('Contact','تواصل معي')][i]}{page===p&&<span/>}</Link>)}</nav>
 <div className="header-controls"><Link className="language-switch" href={route(lang==='en'?'ar':'en',currentPath)} hrefLang={lang==='en'?'ar':'en'} aria-label={t('Switch to Arabic','Switch to English')}>{t('عربي','EN')}</Link><span className="control-divider"/><button className="icon-button theme-toggle" onClick={toggleTheme} aria-label={t('Toggle light and dark appearance','تبديل الوضع الفاتح والداكن')}><Moon className="moon-icon" size={19}/><Sun className="sun-icon" size={19}/></button><button className="icon-button menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="mobile-menu" aria-label={t('Navigation menu','قائمة التنقل')}>{menu?<X/>:<Menu/>}</button></div></div>
 {menu&&<nav id="mobile-menu" className="mobile-nav" aria-label={t('Mobile navigation','قائمة الهاتف')}>{(['home','work','about','contact'] as const).map((p,i)=><Link onClick={()=>setMenu(false)} key={p} href={route(lang,p==='home'?'':p)}>{[t('Home','الرئيسية'),t('Work','الأعمال'),t('About','عنّي'),t('Contact','تواصل معي')][i]}<ArrowUpRight size={19}/></Link>)}</nav>}</header>
 <main id="main" className="page-enter" key={`${lang}-${page}-${slug || ''}`}>
 {page==='home'&&<>
 <section className="hero container"><div className="hero-copy"><div className="availability"><span/>{t('OPEN TO OPPORTUNITIES & FREELANCE','متاحة لفرص العمل والمشاريع المستقلة')}</div><p className="hero-intro">{t('HELLO, I’M SHIMAA.','أهلًا، أنا شيماء.')}</p><h1>{t('Good stories.','حكايات قريبة.')}<br/><em>{t('Real connection.','ومحتوى يوصّل.')}</em></h1><p className="hero-description">{t('I turn ideas into scripts, social content, and videos that speak your audience’s language.','بحوّل الأفكار لسكريبتات ومحتوى سوشيال وفيديوهات تتكلم بلغة جمهورك.')}</p><div className="hero-actions"><Link href={route(lang,'work')} className="button primary">{t('Explore my work','اكتشف أعمالي')}<ArrowUpRight size={18}/></Link><Link href={route(lang,'contact')} className="text-link">{t('Let’s talk','خلّينا نتكلم')}<ArrowRight size={18}/></Link></div><div className="hero-footnote"><span>01 — 03</span><p>{t('WORDS. VISUALS. A LITTLE PERSONALITY.','كلمات. صور. ولمسة شخصية.')}</p></div></div>
 <div className="hero-visual"><div className="portrait-arch"><img className="hero-portrait" src={asset('/images/shimaa-portrait.webp')} alt={t('Shimaa Essam, content creator','شيماء عصام، صانعة محتوى')} width="850" height="1100" fetchPriority="high"/><span className="portrait-caption">{t('A CREATIVE MIND, AT WORK.','فكرة بتاخد شكلها.')}</span></div><span className="orbit-label">{t('IDEAS INTO STORIES','من فكرة لحكاية')}<span>✳</span></span><div className="floating-note"><span className="note-spark">✳</span><div><span>{t('Thoughtfully written.','كتابة بفكرة.')}</span><strong>{t('Made to connect.','ومحتوى يقرّب.')}</strong></div></div><span className="handwritten">{t('a little more human.','بلمسة أقرب.')}<svg viewBox="0 0 100 40" aria-hidden="true"><path d="M4 8 Q35 38 88 15 M77 10 L90 15 L82 25"/></svg></span></div></section>
 <div className="capability-strip"><div className="container"><span>{t('SCRIPTWRITING','كتابة السكريبتات')}</span><i>✳</i><span>{t('SOCIAL CONTENT','محتوى السوشيال')}</span><i>✳</i><span>{t('VIDEO EDITING','مونتاج الفيديو')}</span><i>✳</i><span>{t('CONTENT PLANNING','تخطيط المحتوى')}</span></div></div>
 <div className="container current-brands"><span>{t('CURRENTLY CREATING FOR','بصنع محتوى حاليًا لـ')}</span><a href={brandPages['Creativo Languages Institute']} target="_blank" rel="noopener noreferrer">Creativo Languages Institute <ArrowUpRight size={15}/></a><span className="brand-separator" aria-hidden="true">/</span><a href={brandPages.Espacio} target="_blank" rel="noopener noreferrer">Espacio <ArrowUpRight size={15}/></a></div>
 <section className="section container"><div className="section-top"><SectionIntro lang={lang} eyebrow={t('SELECTED WORK','أعمال مختارة')} title={t('Ideas, out in the world.','أفكار خرجت للنور.')}/><Link href={route(lang,'work')} className="text-link">{t('All projects','كل المشاريع')}<ArrowUpRight size={18}/></Link></div><div className="featured-grid">{[projects[1],projects[0],projects[5],projects[6]].map((p,i)=><ProjectCard key={p.slug} project={p} lang={lang} index={i}/>)}</div></section>
 <section className="reels-section"><div className="container"><div className="section-top"><SectionIntro lang={lang} eyebrow={t('PRESS PLAY','اضغط تشغيل')} title={t('Small screen. Big personality.','فيديو قصير. شخصية واضحة.')} description={t('A few moments from my editing desk.','لقطات من شغلي في كتابة ومونتاج الفيديوهات.')}/><span className="sound-note"><Volume2 size={16}/>{t('You choose when to play.','التشغيل باختيارك.')}</span></div><div className="reel-grid">{['video-04','video-02','video-09'].map(id=><VideoTile key={id} id={id} lang={lang} onPlay={play}/>)}</div></div></section>
 <section className="section container services-section"><SectionIntro lang={lang} eyebrow={t('WHAT I BRING','إزاي أقدر أساعدك')} title={t('From the first idea','من أول فكرة')} description={t('to the final frame.','لآخر لقطة.')}/><div className="services-list">{services.map(s=><div className="service-row" key={s.number}><span className="service-number">{s.number}</span><div><h3>{s.name[lang]}</h3><p>{s.text[lang]}</p></div><ArrowUpRight size={25}/></div>)}</div></section>
 <section className="about-teaser container"><div className="teaser-quote"><span>“</span><p>{t('The best content feels like a conversation.','أحسن محتوى بيحسّسك إن حد بيتكلم معاك.')}<em> — {t('Shimaa','شيماء')}</em></p></div><div><p className="eyebrow">{t('THE PERSON BEHIND THE WORK','مين وراء الشغل؟')}</p><h2>{t('Curious by nature.','فضول بيولّد أفكار.')}<br/><em>{t('Creative by choice.','وإبداع بيحوّلها لمحتوى.')}</em></h2><p>{t('I’m a content creator based in Egypt, working across scripts, social visuals, and short-form video. I enjoy finding a simple, relatable way to tell a brand’s story.','أنا صانعة محتوى من مصر، بشتغل على السكريبتات وتصميمات السوشيال والفيديوهات القصيرة. بحب ألاقي طريقة بسيطة وقريبة أحكي بيها قصة كل براند.')}</p><Link href={route(lang,'about')} className="text-link">{t('A little about me','اعرفني أكتر')}<ArrowUpRight size={18}/></Link></div></section><ContactBand lang={lang}/></>}
 {page==='work'&&!project&&<><section className="page-heading container"><p className="eyebrow">{t('THE PORTFOLIO','معرض الأعمال')}</p><h1>{t('A collection of','مجموعة أفكار')}<br/><em>{t('ideas in action.','اتحوّلت لشغل.')}</em></h1><p>{t('Scripts, social visuals, videos, and the thinking behind them.','سكريبتات وتصميمات وفيديوهات، والتفكير اللي وراهم.')}</p></section><section className="container work-section"><div className="filter-bar" role="group" aria-label={t('Filter projects','تصفية المشاريع')}>{(Object.keys(categories) as (Category|'all')[]).map(c=><button key={c} onClick={()=>setFilter(c)} className={filter===c?'active':''} aria-pressed={filter===c}>{categories[c][lang]}<span>{c==='all'?projects.length:projects.filter(p=>p.category===c).length}</span></button>)}</div><p className="sr-only" role="status">{projects.filter(p=>filter==='all'||p.category===filter).length} {t('projects','مشاريع')}</p><div className="work-grid" key={filter}>{projects.filter(p=>filter==='all'||p.category===filter).map((p,i)=><ProjectCard key={p.slug} project={p} lang={lang} index={i}/>)}</div></section><PublishedWork lang={lang}/><ContactBand lang={lang}/></>}
 {page==='work'&&project&&<>
 <section className="container project-heading"><Link href={route(lang,'work')} className="back-link"><ArrowLeft size={17}/>{t('Back to all work','الرجوع لكل الأعمال')}</Link><p className="eyebrow">{project.brand} <span className="inline-dot"/> {categories[project.category][lang]}</p><h1>{project.title[lang]}</h1><p className="project-subtitle">{project.subtitle[lang]}</p><div className="project-meta"><div><small>{t('BRAND','البراند')}</small><p>{project.brand}</p><a className="brand-page-link text-link" href={brandPages[project.brand]} target="_blank" rel="noopener noreferrer">{t('Visit Facebook page','زيارة صفحة فيسبوك')}<ArrowUpRight size={14}/></a></div><div><small>{t('MY ROLE','دوري')}</small><p>{project.role[lang]}</p></div><div><small>{t('FORMAT','نوع المحتوى')}</small><p>{categories[project.category][lang]}</p></div></div></section>
 <section className="container project-story"><h2>{t('The idea behind it.','الفكرة وراء الشغل.')}</h2><div><p className="story-summary">{project.summary[lang]}</p><div className="story-columns"><div><h3>{t('Who it speaks to','الجمهور')}</h3><p>{project.audience[lang]}</p></div><div><h3>{t('The approach','طريقة التنفيذ')}</h3><p>{project.approach[lang]}</p></div></div></div></section>
 <section className="container project-deliverables"><p className="eyebrow">{t('THE WORK','التنفيذ')}</p>
 {project.videos&&<div className="detail-reel-grid">{project.videos.map(id=><VideoTile key={id} id={id} lang={lang} onPlay={play}/>)}</div>}
 {project.images&&<div className="design-gallery">{project.images.map((id,i)=><div className="design-item" key={id}><button onClick={()=>setMedia({kind:'image',id})} aria-label={`${t('Enlarge design','تكبير التصميم')} ${i+1}`}><img src={asset(`/images/${id}.webp`)} alt={`${project.subtitle[lang]} — ${i+1}`} loading="lazy" width="900" height="900"/><span>{t('View full design','عرض التصميم كاملًا')}<ArrowUpRight size={18}/></span></button>{sourceFor(id)&&<a className="media-source-link" href={sourceFor(id)} target="_blank" rel="noopener noreferrer">{t('View original on Facebook','عرض المنشور الأصلي على فيسبوك')}<ArrowUpRight size={16}/></a>}</div>)}</div>}
 {project.documents&&<div className="document-grid">{project.documents.map(doc=><article className="document-card" key={doc.file}><div className="document-preview"><img src={asset(`/images/${doc.preview}`)} alt={doc.label[lang]} width="600" height="850" loading="lazy"/></div><div><FileText size={22}/><h3>{doc.label[lang]}</h3><p>{t('Audience planning document · Arabic PDF','ملف لتخطيط الجمهور · PDF بالعربية')}</p><a className="text-link" href={asset(`/documents/${doc.file}`)} target="_blank" rel="noopener noreferrer">{t('Read the document','قراءة الملف')}<ArrowUpRight size={18}/></a></div></article>)}</div>}
 </section><section className="section container"><div className="section-top"><SectionIntro lang={lang} eyebrow={t('KEEP EXPLORING','اكتشف المزيد')} title={t('More from the desk.','أعمال تانية من مكتبي.')}/></div><div className="related-grid">{projects.filter(p=>p.slug!==project.slug).slice(0,2).map(p=><ProjectCard key={p.slug} project={p} lang={lang}/>)}</div></section><ContactBand lang={lang}/></>}
 {page==='about'&&<>
 <section className="container about-hero"><div className="about-photo"><img src={asset('/images/shimaa-portrait.webp')} alt={t('Shimaa Essam','شيماء عصام')} width="850" height="1100"/><span className="photo-label">{t('SHIMAA ESSAM / CONTENT CREATOR','شيماء عصام / صانعة محتوى')}</span></div><div><p className="eyebrow">{t('A LITTLE ABOUT ME','نبذة عنّي')}</p><h1>{t('Hi, I’m','أهلًا، أنا')}<br/><em>{t('Shimaa.','شيماء.')}</em></h1><p className="large-copy">{t('I find the story, shape the words, and bring the idea to life.','بلاقي الحكاية، وأصيغ الكلمات، وأحوّل الفكرة لمحتوى.')}</p><p>{t('I’m a content creator based in Banha, Egypt. My work brings together social copy, scripts, visual design, and video editing, with a focus on clear messages and relatable ideas.','أنا صانعة محتوى من بنها، مصر. شغلي بيجمع بين كتابة محتوى السوشيال والسكريبتات والتصميم والمونتاج، مع تركيز على الرسائل الواضحة والأفكار القريبة من الجمهور.')}</p><p>{t('I’ve created content for language learning and training, moving between educational ideas, promotional posts, and lighter social moments. I’m open to a new team, a new project, or a thoughtful collaboration.','اشتغلت على محتوى لتعلّم اللغات والتدريب، بين أفكار تعليمية ومنشورات تعريفية ومواقف خفيفة للسوشيال. ومهتمة بفرص الانضمام لفريق جديد أو التعاون في مشاريع مستقلة.')}</p><a href={asset('/documents/Shimaa-Essam-CV.pdf')} download className="button primary">{t('Download my CV','تحميل السيرة الذاتية')}<Download size={18}/></a></div></section>
 <section className="section container experience-section"><SectionIntro lang={lang} eyebrow={t('EXPERIENCE','الخبرة')} title={t('Creating, learning, refining.','بكتب، وبنفّذ، وبتعلّم.')}/><div className="experience-entry"><div><span className="eyebrow">{t('JANUARY 2025 — PRESENT','يناير ٢٠٢٥ — حتى الآن')}</span><h3>Creativo Languages Institute</h3><a className="text-link brand-page-link" href={brandPages['Creativo Languages Institute']} target="_blank" rel="noopener noreferrer">{t('View Facebook page','زيارة صفحة فيسبوك')}<ArrowUpRight size={15}/></a><p>{t('Content creation · Social media · Sales support','صناعة المحتوى · السوشيال ميديا · دعم المبيعات')}</p></div><ul><li>{t('Writing scripts for reels, posts, and marketing content.','كتابة سكريبتات الريلز والمنشورات والمحتوى التسويقي.')}</li><li>{t('Planning content calendars and developing ideas with the team.','تخطيط جداول المحتوى وتطوير الأفكار مع الفريق.')}</li><li>{t('Designing social visuals and editing short-form video.','تصميم محتوى السوشيال ومونتاج الفيديوهات القصيرة.')}</li><li>{t('Supporting lead follow-up and customer communication.','دعم متابعة العملاء المحتملين والتواصل معهم.')}</li></ul></div><div className="experience-entry"><div><span className="eyebrow">{t('JANUARY 2025 — PRESENT','يناير ٢٠٢٥ — حتى الآن')}</span><h3>Espacio</h3><p>{t('Content creator · Education & training','صانعة محتوى · التعليم والتدريب')}</p><a className="text-link brand-page-link" href={brandPages.Espacio} target="_blank" rel="noopener noreferrer">{t('View Facebook page','زيارة صفحة فيسبوك')}<ArrowUpRight size={15}/></a></div><ul><li>{t('Creating social content for practical education and training.','صناعة محتوى للسوشيال عن التعليم العملي والتدريب.')}</li><li>{t('Writing scripts and editing short-form promotional videos.','كتابة السكريبتات ومونتاج الفيديوهات التعريفية القصيرة.')}</li><li>{t('Developing visual designs and course-related messages.','تصميم محتوى بصري ورسائل تعريفية للكورسات.')}</li></ul></div></section>
 <section className="section container"><SectionIntro lang={lang} eyebrow={t('HOW I CAN HELP','خدماتي')} title={t('One idea. Different ways to tell it.','فكرة واحدة. طرق كتير نحكيها.')}/><div className="service-cards">{services.map(s=><article key={s.number}><span className="eyebrow">{s.number} / {s.name[lang]}</span><h3>{s.title[lang]}</h3><p>{s.text[lang]}</p></article>)}</div><div className="tools-row"><span>{t('EVERYDAY TOOLS','أدوات شغلي')}</span><strong>Canva</strong><strong>CapCut</strong><strong>Google Sheets</strong><strong>Microsoft Office</strong></div></section><ContactBand lang={lang}/></>}
 {page==='contact'&&<ContactPage lang={lang}/>}
 </main><footer className="footer container"><Link className="wordmark" href={route(lang)}><span className="monogram">s.</span><span>{t('Shimaa Essam','شيماء عصام')}<small>{t('CONTENT CREATOR','صانعة محتوى')}</small></span></Link><p>© {new Date().getFullYear()} {t('Shimaa Essam. Created with intention.','شيماء عصام. محتوى بفكرة.')}</p><div><a href={contact.linkedin} target="_blank" rel="noopener noreferrer" aria-label="LinkedIn"><Linkedin size={18}/></a><a href={`mailto:${contact.email}`} aria-label={t('Email Shimaa','راسل شيماء')}><Mail size={19}/></a><a href={contact.whatsapp(lang)} target="_blank" rel="noopener noreferrer" aria-label="WhatsApp"><MessageCircle size={19}/></a></div></footer>
 <a href={contact.whatsapp(lang)} target="_blank" rel="noopener noreferrer" className="floating-whatsapp" aria-label={t('Chat with Shimaa on WhatsApp','تواصل مع شيماء على واتساب')}><MessageCircle size={25}/><span>{t('Let’s talk','نتكلم؟')}</span></a>
 {media&&<dialog ref={dialog} className={`media-dialog ${media.kind}`} aria-label={media.kind==='video'?videoTitles[media.id][lang]:t('Full design','التصميم كاملًا')} onCancel={()=>setMedia(null)} onClick={event=>{if(event.target===event.currentTarget)setMedia(null)}}><button autoFocus className="dialog-close icon-button" onClick={()=>setMedia(null)} aria-label={t('Close preview','إغلاق المعاينة')}><X/></button><div className="dialog-body">{media.kind==='video'?<VideoPlayer key={media.id} id={media.id} lang={lang}/>:<img src={asset(`/images/${media.id}.webp`)} alt={t('Social media design by Shimaa Essam','تصميم سوشيال ميديا لشيماء عصام')}/>}</div></dialog>}
 </div>
}
